spring:
  application:
    name: service-2 # Service registers under this name

server:
  port: 8082
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/

info:
  app:
    name: service-2
    description: Spring Cloud Application Managing Person Instances
    version: 1.0-SNAPSHOT